# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-hmac/all/ruby-hmac.rbi
#
# ruby-hmac-0.4.0
module HMAC
end
class HMAC::Base
  def <<(text); end
  def check_status; end
  def digest; end
  def hexdigest; end
  def initialize(algorithm, block_size, output_length, key); end
  def reset_key; end
  def self.digest(key, text); end
  def self.hexdigest(key, text); end
  def self.new(*arg0); end
  def set_key(key); end
  def to_s; end
  def update(text); end
end
class HMAC::SHA1 < HMAC::Base
  def initialize(key = nil); end
  def self.digest(key, text); end
  def self.hexdigest(key, text); end
  def self.new(*arg0); end
end
